### ISSUE TITLE
v1 Task List

### ISSUE THREAD

**Issue by sushi-su** [QNAV/RuoYi-X-Umi#2]
- [ ] 系统管理
  - [ ] 用户管理
  - [ ] 角色管理 @sushi-su 
  - [ ] 菜单管理 @sushi-su 
  - [ ] 部门管理 @sushi-su 
  - [ ] 岗位管理 @sushi-su 
  - [ ] 字典管理
  - [ ] 参数管理
  - [ ] 通知公告
  - [ ] 日志管理
    - [ ] 操作日志
    - [ ] 登录日志
  - [ ] 文件管理
- [ ] 系统监控
  - [ ] 在线用户 @sushi-su 
  - [ ] 数据监控
  - [ ] 缓存监控
  - [ ] Admin监控
  - [ ] 任务调度中心
- [ ]  系统工具
  - [ ] 表单构建
  - [ ] 代码生成 @sushi-su 
  - [ ] 系统接口
